version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias para Build..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Copiando artefactos..."
      - mkdir output
      - cp -r * output/

artifacts:
  files:
    - '**/*'
  base-directory: output
